---
# Items that apply to ALL profiles:
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/
#      defaultZone: http://localhost:8011/eureka/,http://localhost:8012/eureka/,http://localhost:8013/eureka/

---
spring.config.activate.on-profile: kyiv
temperatures: 12,14,16,18,20,22,24

---
spring.config.activate.on-profile: washington
temperatures: 15,17,19,21,23,25,27

---
spring.config.activate.on-profile: london
temperatures: 10,12,14,15,17,19,20

---
spring.config.activate.on-profile: berlin
temperatures: 11,13,15,17,19,21,23

---
spring.config.activate.on-profile: paris
temperatures: 13,15,17,19,21,23,25
